### PR TITLE
Peaks v1.1

### PR DESCRIPTION
**Pull request by boourns**
@timchurches 

This ports v1.1 of peaks code to Peaks DMC.
I started with the code from @johnfolkesson's branch, and then applied https://github.com/pichenettes/eurorack/commit/26f0ec7a60b94b4c73b6cd04eb786cbf0d42b7ef

- fixed the rejects
- made similar changes to the other processors
- tested and fixed the algorithms I broke in the process

At this point I've tested all the DMC functionality in Twin mode, but not split or expert.  Also, I mostly tested just Ch1.

### CODE REVIEW

**Comment by boourns** [comment]
I just noticed that upstream has bumped `stmlib` dependency, so I've bumped it here.  

This branch works without stmlib bumped, but peaks tests won't compile.  Some of the commits seem related to the peaks update so if possible it'd be better to include it in the patch, but it also means that this PR now affects the other alternate firmwares in this repo.

**Comment by timchurches** [comment]
Unfortunately, my ancient Mac Pro which had my Mutables toolchain on it has
died (or at least it refuses to boot, although has mirrored discs and
back-ups so recoverable, but no time to fiddle with it right now), so I'll
need to set up a new one on my MacBook Pro. So no progress over the
weekend. It shouldn't take long to install the toolchain. I have
theST/linkV2  programmer hooked up to my test module again (I had
temporarily misplaced it).

**Comment by boourns** [comment]
I'm in no rush, take your time.

I realized there's like 50k of space so I'm working on a sample-based drum player.

**Comment by timchurches** [comment]
Someone went to the trouble of recording some samples, in a professional
studio with high-end mikes etc, for inclusion in DMC. I'll see if I can
find them and send them to you.

**Comment by timchurches** [comment]
Here we are: hi-hat samples recorded for DMC, already down-sampled, plus a demo of them in a loop.

[loop1.m4a.zip](https://github.com/timchurches/Mutated-Mutables/files/1151487/loop1.m4a.zip)

[downsample.zip](https://github.com/timchurches/Mutated-Mutables/files/1151486/downsample.zip)


Need to credit Michael Brawer with doing these, but they are unencumbered and free for use in DMC.

**Comment by boourns** [comment]
I opened an issue describing the sample player I've got in mind as I won't be adding it to this PR, I'm interested in your thoughts.

**Comment by boourns** [comment]
I'm on vacation until end of July and I'm leaving my phone (and synths :( ) at home, so don't expect any response until then.  Cheers!

**Comment by boourns** [comment]
@timchurches IMO this PR should get merged and shipped soon as it fixes the bugs discussed in the muffwiggler thread where the CPU lags and the LFOs mess up

The sample player can sit as a PR for now as (IMO) it could use better samples than what I've managed to put together.  It's worth a play though.

**Comment by timchurches** [comment]
Ok, thanks, will review it tonight.

**Comment by johnfolkesson** [comment]
Hey just to let you guys know I´m running the code from my original PR on 2 different peaks and everything appears to be working just fine.

**Comment by skinlayers** [comment]
@timchurches @boourns I noticed this PR was merged ~3 years ago, but a new binary was never released. I've seen  @forestcaver 's binary of @johnfolkesson 's v3 calibration PR floating out in the wild, among others. I was wondering if there were any known issues after PR #2 was merged that would prevent binary distribution?

I've worked out how to compile the latest code using [pichenettes/mutable-dev-environment](https://github.com/pichenettes/mutable-dev-environment), and was wondering if there was any reason I shouldn't distribute a hex and/or wav version for those requesting it?

Thank you!

**Pull request merged**
